---
title: "Q&A"
author: "糖炒栗子"
date: "2024-08-19"
format: html
editor: visual
---

> *每一个稀奇古怪的问题背后,都有一个惨痛的故事*

## 1. 支援卡是什么？

所有不可分解卡都属于[**支援卡**](https://lizicup.netlify.app/基础规则/支援卡/支援卡.html)，支援卡在比赛中只能使用UR及SR和部分N，R卡（详情请参考[**禁卡表**](https://lizicup.netlify.app/基础规则/禁卡表/禁卡表.html)）

### 1.1 禁卡带了会怎么样？

小局判负

## 2. 比赛可以合卡/买小包吗？

不可以，合卡/买小包视为犯规，经过查证后直接判负，具体可参考[“比赛基础规则”](https://lizicup.netlify.app/基础规则/基本/基本)，当前初始数据为19抽和1合成，最终数据应符合329（19+310）抽和1合成，如有初始数据不对的情况请在收取初始号当天说明

### 2.1 签到活动送券怎么办

在科乐美周年庆活动期间请直接领取，如果最后总抽数不是19请在抽完320抽后自行抽取大包补充至339

## 3. 初始号发放吗？

初始号在玩家报名并与主办方核对成功后发放，Steam端需要Steam入库号的请在发放时主动说明，同时请将游戏内ID改成与群名片及报名自定义名称相同便于核对

## 4. 可以买预组吗？

不可以，钻石只能用来购买320抽大包或桌宠、桌垫和卡套

## 5. 比赛中可以更改卡组吗？需要上传卡组吗？

可以在比赛中调整卡组，最后如出轮需要向主办方提交：最后一场比赛使用的卡组，便于编写战报（不需要上传卡组，比赛结束后截图**私聊主办方**提交）

## 6. 相剑预组可以找人填码激活码？

不可以，同问题 【4. 可以买预组吗】

## 7. 可以通过任务获得部分UR、SR支援卡（如：光之护封剑、链接蜘蛛）吗？

可以，经检查历届战报，此类卡使用率较低故不设限制

## 8. 可以偷偷换号吗？

不可以，比赛结束后将公布所有人账号信息，如有赛后核对不上被举报者将被禁赛

## 9. 别人偷偷合卡怎么办？

如对他人卡组有疑问请在赛后自行查询、提供合卡证据举报

## 10. 别人偷偷抽小包怎么办？

如对他人卡组有疑问请在赛后自行查询、提供抽小包证据举报（小包卡组在获得排序内粘连，众多同一小包nr卡堆叠等特点）

## 11. 有其他比赛冲突可以先和对手打吗？

可以，第一轮对阵表一般会在报名结束发放，如果对手同意可以提前约战并填写成绩

P.S. 对手提前陪打是情分，不是本分

### 11.1 对战表周五与周六不一样怎么办

周六为确认退赛人员后的最终对战表，若提前约战请确保双方都无退赛情况
